# Generated by Django 4.2.6 on 2023-10-20 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.CharField(max_length=1000000)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 16, 22, 22, 247687, tzinfo=datetime.timezone.utc), verbose_name='entry date')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('entry_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry')),
            ],
        ),
    ]
